runs-on: ubuntu-latest

steps:
  - name: Check out repository
    uses: actions/checkout@v2

  - name: Compile Java Code
    run: javac *.java

  - name: Run JUnit Tests
    run: java -cp .:/path/to/junit.jar:/path/to/hamcrest-core.jar org.junit.runner.JUnitCore ClientTest.java
